FROM mysql:8.0.36
EXPOSE 3306

FROM pgvector/pgvector:0.7.0-pg15
EXPOSE 5432

FROM mongo:5.0.18
EXPOSE 27017

FROM ghcr.io/labring/fastgpt:v4.8.1
EXPOSE 3000

FROM ghcr.io/songquanpeng/one-api:latest
EXPOSE 3001